package com.example;

public class MyFirstException {


    public int divide(int numberToDivide, int numberToDivideBy)
    throws Exception{
        if(numberToDivideBy == 0){
            throw new Exception("Cannot divide by 0");
        }
        return numberToDivide / numberToDivideBy;
    }
 


public void callDivide(){
    try {
        int result = divide(2,1);
        System.out.println(result);
    } catch (Exception e) {
        //do something clever with the exception
        System.out.println(e.getMessage());
    }
    System.out.println("Division attempt done");
}

public static void main(String args[]){
	MyFirstException myFirstException = new MyFirstException();
	myFirstException.callDivide();
}
}